### ISSUE TITLE
Make date URLs work

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/wp-pwa-plugin#17]
> **Hacer las URLs de archivos por fecha funcionales en la versión Worona**

> Puede afectar a indexación. Aunque en adslzone.tv actualmente están desindexadas, sí llevan el atributo "follow" para seguir los enlaces. En otras webs es posible que estén indexadas. En cualquier caso, Google tiene esas URLs en su "lista" y las va a rastrear

**Comment by luisherranz** [comment]
They don't render the PWA until it's ready.
