### ISSUE TITLE
Add support for AMP

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/wp-pwa-plugin#22]
- [x] AMP (_Disabled / Only Posts / ~All~*_ ) 
- [x] **AMP Server** (In advanced settings, default: `https://amp.wp-pwa.com`)
- [x] Inject **amphtml link** on every page (https://www.ampproject.org/docs/guides/discovery)
  
Things to investigate:
 - Queries in AMP, for example utm campaigns. Are they redirected?
 - Google Analytics in AMP, what we need to configure.
_____________
*_We will launch just with Posts, and will add the rest of the content in a future version_

**Comment by luisherranz** [comment]
Links added to the amphtml link should be like:
`https://amp.wp-pwa.com/amp/www.example.com/final-post-permalink?QUERY`

QUERY should be the same we are using to fetch our pwa server:
https://github.com/wp-pwa/wp-pwa-plugin/blob/master/injector/wp-pwa-injector.php

For example:
 - home: `?siteId=xxx&env=pre|prod&listType=latest&listId=post&page=1`
 - post: `?siteId=xxx&env=pre|prodsingleType=post&singleId=X`
 - page: `?siteId=xxx&env=pre|prodsingleType=page&singleId=X`
 - category: `siteId=xxx&env=pre|prodlistType=category&listId=X&page=1`
 - tag: `siteId=xxx&env=pre|prodlistType=tag&listId=X&page=1`

etc.

**Comment by Poliuk** [comment]
The plugin is almost finished, we just need to test it together with the PWA infrastructure. I'd suggest to test it in this branch before merging it into dev. 

@orballo can you take a look to this two things and test it with your part?

- Queries in AMP, for example utm campaigns. Are they redirected?
- Google Analytics in AMP, what we need to configure.

Let @luisherranz or me know if you need any help 😊
