### ISSUE TITLE
Add 'Force FrontPage to retrieve Latest posts' option

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/wp-pwa-plugin#29]
- [x] Added in the Advanced settings menu, as a checkbox (@Poliuk)
 - [ ] Implemented in injector (@luisherranz)

**Comment by Poliuk** [comment]
@luisherranz you can retrieve the value using `$settings['wp_pwa_force_frontpage']`. The code is available in the `force-frontpage-latest-posts` branch
