### ISSUE TITLE
Add exclude urls

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/wp-pwa-plugin#31]
- [x] Add a field in the dashboard to enter some regexps (one per line, for example) and save it to the database.
- [ ] If any of those regexps matches the url, don't load the PWA (unless force=true)

**Comment by Poliuk** [comment]
@luisherranz the regexps are being stored as an array in `$settings['wp_pwa_excludes'];` . You can continue this in the branch `excludes-31`
