### ISSUE TITLE
Check W3 Total Cache

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/wp-pwa-plugin#36]
Check why W3 Total Cache is caching the WP-API and how can we deactivate it.

**Comment by Poliuk** [comment]
It looks like `HNET` is using a varnish in addition to W3 Total Cache. So we can't exclude the WP-API Urls using the plugin settings. 

In any case, if we face a similar issue with this plugin in the future. There is a native option to exclude URLs using RegExps:

![Screen Shot 2018-01-23 at 13.02.38.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58b46c76cb082b1a00bab064/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226456f06b7191a379ec0c2b53415c46be5d4a1f06a3a3dc78e2a436628f0d0defd16d0d7cc03a43fdeb8a1fbf00ec76dd4a81e5bd9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec95ef14be84450a6163463f43b.png)
