### ISSUE TITLE
D2 posts with no content

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/wp-pwa-plugin#54]
It looks like the WP-API doesn't output any content on D2 posts:
https://decoracion2.com/wp-json/wp/v2/posts/68314

Maybe it's the latest version of our plugin?

**Comment by luisherranz** [comment]
@Poliuk could you please take care of this?

**Comment by luisherranz** [comment]
Another one: 
https://decoracion2.com/wp-json/wp/v2/posts/93668

**Comment by Poliuk** [comment]
@luisherranz I've just contacted him, I'll keep you posted

**Comment by luisherranz** [comment]
ok, thanks @Poliuk !

**Comment by Poliuk** [comment]
- make the purifier an advanced setting 
- check if the string is empty before returning it ( https://github.com/wp-pwa/wp-pwa-plugin/blob/master/wp-pwa.php#L189)
