### ISSUE TITLE
html purifier is creating a conflict in some wordpresses

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/wp-pwa-plugin#67]
The plugin is crashing with ERROR 500 in some installations because we declare a PHP class that is being declared by other plugins.  

Check if we can change the name of the class. 

> [05-Jun-2018 09:36:52 UTC] PHP Fatal error:  Cannot declare class simple_html_dom_node, because the name is already in use in /var/www/vhosts/sobrehistoria.com/httpdocs/wp-content/plugins/wp-pwa/libs/simple_html_dom.php on line 115

**Comment by luisherranz** [comment]
Solved in #e4ae5da29473be0769de116b5a39b7dd3a818bfe
