### ISSUE TITLE
Check if we can integrate "in text video ads"

### ISSUE THREAD

**Issue by Poliuk** [wp-pwa/wp-pwa-plugin#69]
One of our customers wants to integrate "in text video ads". 

This is the code they have provided:

```
<script async type="application/javascript" src="https://platform.sunmedia.tv/integrations/2ab00e3c-c9ac-4321-b6b2-bd40a35b1219.js"></script>
```

> **example url:** (mobile version) https://modaellos.com/los-mejores-cortes-de-cabello-para-hombres-de-acuerdo-a-tu-tipo-de-rostro/

![Screen Shot 2018-06-05 at 16.00.35.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58b46c76cb082b1a00bab064/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256454f66b7191a379e90c2b51415c4bbe5d4a1f06a3a3dc78e2a436628f0d0defd16d0d7cc03a43fdeb8a1fbf00ec76dd4a81e5bd9850d2aa6c7bb3d4d216744b470a83ed5c3caa984eca50f44be64e54a31b346bf43b.png)

![Screen Shot 2018-06-05 at 16.00.40.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58b46c76cb082b1a00bab064/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256454f66b7191a379e90c2b51415b4ebe5d4a1f06a3a3dc78e2a436628f0d0defd16d0d7cc03a43fdeb8a1fbf00ec76dd4a81e5bd9850d2aa6c7bb3d4d216744b470a83ed5c3caa984eca50f44be64e54a31b3562f43b.png)

**Comment by orballo** [comment]
@luisherranz Just in case you want to check this tomorrow before I arrive. Basically adds support to inject a `sunmedia` script instead of an ad, and prevents the use of this ads in AMP, as they are not supported.
