### ISSUE TITLE
Venue Map not zoomable

### ISSUE THREAD

**Issue by philliproth** [wp-pwa/wp-pwa-plugin#72]
It would be nice to be able to zoom the Venue Map.

**Comment by luisherranz** [comment]
Welcome and thanks for your suggestion @philliproth :)

We haven't had time to implement pinch zoom in the PWA, but if you click on the image your browser will load the jpg image and you can zoom it. 

For other WCEU-PWA related issues, please use this repository:
https://github.com/frontity/wordcamp-theme/issues
