### ISSUE TITLE
Get rid of site-info and add that to the injector

### ISSUE THREAD

**Issue by luisherranz** [wp-pwa/wp-pwa-plugin#8]

**Comment by Poliuk** [comment]
@luisherranz the `site-info` parameters are now passed through a query to the injector (same as #9 ). I let you close the issue.

I've also opened an issue (https://github.com/worona/wp-org-connection-app-extension-worona/issues/17) to refactor this in the pwa-side.

**Comment by Poliuk** [comment]
We still need it, with the "per_page" available here.

**Comment by luisherranz** [comment]
We went back to the old behaviour.
